### ISSUE TITLE
Add '@babel/core'

### ISSUE THREAD

**Issue by holtwick** [bdbch/create-tiptap-extension#10]
With my pnpm setup secondar dependencies are not solved automatically. Therefore I get:
```
[!] Error: Cannot find module '@babel/core'
```

An `nmp i -D @babel/core` solved the issue. Yoy might want to add the dependency to your builder as well? Thanks.

**Comment by bdbch** [comment]
Thanks for the issue! I'll look into it!

**Comment by bdbch** [comment]
@holtwick just released 1.1.3 - should work now. Thanks for letting me know.
